---
title: "SE"
author: "Axel Zagal"
date: "24/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## Lets build our first SummarizedExperiment object
library("SummarizedExperiment")
## ?SummarizedExperiment

## De los ejemplos en la ayuda oficial

## Creamos los datos para nuestro objeto de tipo SummarizedExperiment
## para 200 genes a lo largo de 6 muestras
nrows <- 200
ncols <- 6
## Números al azar de cuentas
set.seed(20210223)
counts <- matrix(runif(nrows * ncols, 1, 1e4), nrows)
## Información de nuestros genes
rowRanges <- GRanges(
    rep(c("chr1", "chr2"), c(50, 150)),
    IRanges(floor(runif(200, 1e5, 1e6)), width = 100),
    strand = sample(c("+", "-"), 200, TRUE),
    feature_id = sprintf("ID%03d", 1:200)
)
names(rowRanges) <- paste0("gene_", seq_len(length(rowRanges)))
## Información de nuestras muestras
colData <- DataFrame(
    Treatment = rep(c("ChIP", "Input"), 3),
    row.names = LETTERS[1:6]
)
## Juntamos ahora toda la información en un solo objeto de R
rse <- SummarizedExperiment(
    assays = SimpleList(counts = counts),
    rowRanges = rowRanges,
    colData = colData
)

## Exploremos el objeto resultante
rse
```
```{r}
dim(rse)

dimnames(rse)

assayNames(rse)

head(assay(rse))

rowRanges(rse)
```

```{r}
rse[1:2, ]
head(assay(rse[1:2,]))
```
Al acceder únicamente a los renglones 1 y 2, nos muestra un subset con  únicamente 
los primeros dos genes

```{r}
rse[, c("A", "D", "F")]
head(assay(rse[,c("A","D","F")]))
```
Este otro subset nos muestra los 200 genes con los features A, D y F

```{r}
library("iSEE")
iSEE::iSEE(rse)
```

```{r}
sce_layer <- spatialLIBD::fetch_data("sce_layer")
```
```{r}
iSEE::iSEE(sce_layer)
```
En el heatmap pudimos ver que los genes MOBP y MBP se expresan más en la capa WM

# Recount

```{r}
library("recount3")
human_projects <- available_projects()
```
```{r}
proj_info <- subset(
    human_projects,
    project == "SRP009615" & project_type == "data_sources"
)

rse_gene_SRP009615 <- create_rse(proj_info)
```
```{r}
## Explora los proyectos disponibles de forma interactiva
proj_info_interactive <- interactiveDisplayBase::display(human_projects)
## Selecciona un solo renglón en la tabla y da click en "send".

## Aquí verificamos que solo seleccionaste un solo renglón.
stopifnot(nrow(proj_info_interactive) == 1)
## Crea el objeto RSE
rse_gene_interactive <- create_rse(proj_info_interactive)
```

```{r}
rse_gene_SRP009615 <- expand_sra_attributes(rse_gene_SRP009615)
colData(rse_gene_SRP009615)[
    ,
    grepl("^sra_attribute", colnames(colData(rse_gene_SRP009615)))
]
```
```{r}
iSEE::iSEE(rse_gene_SRP009615)
```

